# Generated by Django 4.2.4 on 2023-09-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appat', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='apPat', max_length=255, null=True)),
                ('apmat', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='apMat', max_length=255, null=True)),
                ('nombres', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=255, null=True)),
                ('contrasena', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=225, null=True)),
            ],
            options={
                'db_table': 'datos',
                'managed': False,
            },
        ),
    ]
